name: TDD_Exercise
description: A sample command-line application
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  exportable: '>=0.1.0 <0.2.0'
  mock: '>=0.11.0+2 <0.12.0'
  redis_client: any
  unittest: any
  uuid: 0.5.0
